name: CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Compile binary
        run: go build -v ./

      - name: Run Tests
        run: go test -v -cover -race ./...

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Get short SHA
        run: echo "REVISION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Get version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/fyne-cross
          key: ${{ runner.os }}-fyne-cache-${{ hashFiles('**/go.sum') }}

      - name: Install Fyne-cross
        run: |
          go install github.com/fyne-io/fyne-cross@latest

      - name: Package for Windows
        run: fyne-cross windows -tags=gui -arch=amd64

      - name: Move Windows-amd64
        run: |
          mkdir dist
          mv \
            "fyne-cross/dist/windows-amd64/Dispel Multi.exe.zip" \
            "dist/DispelMulti_${{ env.REVISION }}.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/DispelMulti_${{ env.REVISION }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/DispelMulti_${{ env.TAG_VERSION }}.zip
