name: container

on:
  workflow_dispatch:
    inputs: { }

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Get build data
        run: |
          echo "BUILD_REVISION=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Use short SHA as a version number
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "BUILD_VERSION=devel-${BUILD_REVISION}" >> $GITHUB_ENV

      - name: Use tag as a version number
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "BUILD_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Go binary
        run: |
          go build -ldflags="-s -w -X main.version=${BUILD_VERSION} -X main.commit=${BUILD_REVISION} -X main.date=${BUILD_TIME}" -o gladiator .
        env:
          CGO_ENABLED: "0"
          GOOS: "linux"
          GOARCH: "amd64"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: |
          docker build \
            --build-arg BUILD_DATE=$BUILD_TIME \
            --build-arg VERSION=$BUILD_VERSION \
            --build-arg GIT_COMMIT=$BUILD_REVISION \
            -t $IMAGE_NAME .
        env:
          IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/gladiator:latest"